### ISSUE TITLE
How do you escape $ when appearing in the value?

### ISSUE THREAD

**Issue by infamousjoeg** [cyberark/summon#115]
I'm trying to inject a password hash containing `$` into a process and it is failing since I cannot find any reference of how to escape a `$` in YAML.

Trying to escape with `\` gives `Variable b31f6a9bbdc53ed2ce0c4ca551da355dba2734419ee44a2bfeba9c1d99368885 not declared!`.

Trying to escape with double `$` causes the `$` to disappear.

**Comment by sgnn7** [comment]
Hey @infamousjoeg  - checked this out and `$$` should be fine. See https://github.com/cyberark/summon/pull/116 for the test I added for it. Closing this for now but reopen it if there's something that I missed.
