### ISSUE TITLE
Summon can't parse empty tags in YAML with multiple keys

### ISSUE THREAD

**Issue by izgeri** [cyberark/summon#124]
@infamousjoeg shared that he can run summon with YAML that includes empty references [here](https://discuss.cyberarkcommons.org/t/securing-oauth-tokens-using-summon/551/3?u=izgerij)

but I just tried to run summon with secrets.yml
```
GITHUB_USERNAME:
GITHUB_AUTH_TOKEN: !var github/api_token
```
and it errored
```
OOPS! {Kind:8 Style:0 Tag:!!null Value: Anchor: Alias:<nil> Content:[] HeadComment: LineComment: FootComment: Line:1 Column:17}
```

which appears to come from https://github.com/cyberark/summon/blob/3a33a5fcca52d43e1e6007e9075e8989acb2ee53/secretsyml/secretsyml.go#L102

I would expect that if I have an empty tag/secret in the secrets.yml, Summon would set an empty env var or set the env var to the value from my environment (if set). I haven't been able to dig into why it errored, but I think this is a bug considering how it behaved for Joe when his YAML was a single key with no tag/secret.

**Comment by sgnn7** [comment]
@infamousjoeg We got a fix in now but I'm not going to build a release for it unless you need it now since it's a bit of a time-consuming task. Ping me if you need that done.

**Comment by izgeri** [comment]
since it's not available in a release yet, I'm going to reopen it for now - but maybe these kinds of thing should have a `pending-release` label (or similar)

**Comment by micahlee** [comment]
As a heads up, even with just the "Connected to" reference, GH still auto-closed this when I merged the PR(#125).

**Comment by izgeri** [comment]
Thanks @micahlee - that's gtk

**Comment by sgnn7** [comment]
Closing as "released". v0.8.1 can be found [here](https://github.com/cyberark/summon/releases/tag/v0.8.1).
