### ISSUE TITLE
standardised CHANGELOG exists, and is validated via pipeline

### ISSUE THREAD

**Issue by doodlesbykumbi** [cyberark/summon#126]
If the repo has a changelog that doesn't meet the standard, do try to change earlier entries to match the standard.
If the repo doesn't have a changelog use this as a starter:
```
# Changelog
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/en/1.0.0/)
and this project adheres to [Semantic Versioning](http://semver.org/spec/v2.0.0.html).

## [Unreleased]
```

## Acceptance criteria
- [ ] CHANGELOG.md exists and follows the KeepAChangeLog format. For reference consult https://github.com/cyberark/conjur/blob/master/CHANGELOG.md.
- [ ] Add parse-changelog validation step to Jenkinsfile. For reference consult  https://github.com/cyberark/conjur/blob/master/Jenkinsfile#L27.

**Comment by JakeQuilty** [comment]
Link to PR: https://github.com/cyberark/summon/pull/128
