### ISSUE TITLE
Support for portable installation: search provider folder next to summon executable

### ISSUE THREAD

**Issue by ckolumbus** [cyberark/summon#164]
## Is your feature request related to a problem? Please describe

summon is a great go tool: only one executable to put somewhere and execute. Only the default search path 
for providers is within the system directories of the respective operating system.
If you want to to use any provider without having administrator/root  rights you always have to give the full path to the
provider or set the `SUMMON_PROVIDER` environment variable.

Also the default provider mechanism, if only one provider exists take this one, does not work either if the provider is not installed into the system directory.

## Describe the solution you would like

I propose to extend the search for provider directory in such a way that if the system provider path does not exist another
provider directory right next to the `summon`  executable is searched as well.

With the proposed approach anyone without admin right can have short provider names and the default provider mechanism 
work.

## Describe alternatives you have considered

As mentioned above I was trying the mechanisms that `summon` provides out of the box (env variable & provider parameter) with the drawback explained above.
 
Other implementation possibilities could be to have an installer that updates the search path during the installation process so that summon itself search differently. Together with a installation target directory and an installer that can be executed without admin right could provide the same functionality

The proposed solution seems to be the simplest providing non-admin install and auto-provider-search capabilities and does not depend on any further adaption, eg. the installer.

## Additional context

The draft implementation for review and as basis for further discussion is available as #163.

**Comment by boazmichaely** [comment]
Published in [CyberArk Aha! idea portal](https://cyberark.ideas.aha.io/ideas/SCR-I-87)

**Comment by ckolumbus** [comment]
This can be closed as #218  implements this feature.
