### ISSUE TITLE
Install script error paths aren't displaying proper error info

### ISSUE THREAD

**Issue by sgnn7** [cyberark/summon#171]
## Summary
We use a helper method `error` in [`install.sh`](https://github.com/cyberark/summon/blob/master/install.sh) but that function is not defined anywhere in the script.

## Steps to Reproduce
1. Run an `ubuntu:latest` container
2. Try to run the installer script

## Expected Results
```
ERROR: Could not find wget or curl
Exiting installer
```

## Actual Results (including error logs, if applicable)
`./install.sh: line xx: error: command not found `

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
v0.8.2

## Environment setup
N/A

## Additional Information
N/A

**Comment by izgeri** [comment]
just noting that I removed some labels that are intended for dedicated efforts to improve devex or quality - this is just a bug.

**Comment by sgnn7** [comment]
Closed via #172
