### ISSUE TITLE
Summon builds are unstable

### ISSUE THREAD

**Issue by izgeri** [cyberark/summon#193]

**Comment by rpothier** [comment]
The failed test is  TestJoinEnv()
The failure is:
Failures:
  * /summon/internal/command/action_test.go 
  Line 85:
  Expected: 'foo=bar
  baz=qux
  '
  Actual:   'baz=qux
  foo=bar
  '
  (Should be equal)

This was fixed by #195 as noted above.

**Comment by izgeri** [comment]
This looks to have been resolved - closing this issue now.
