### ISSUE TITLE
Broken links in the gh-pages

### ISSUE THREAD

**Issue by dividedmind** [cyberark/summon#47]
https://cyberark.github.io/summon/ -- see for example the docker example link.

Also the Examples and the Providers links
![image](https://user-images.githubusercontent.com/13609044/29574716-0d98219e-876b-11e7-99eb-c20a08360e67.png)

(Issue created on behalf of @jeniaSakirko.)

**Comment by doodlesbykumbi** [comment]
#48 fixes this
