### ISSUE TITLE
`summon --version` should also show version of installed providers

### ISSUE THREAD

**Issue by ryanprior** [cyberark/summon#56]
At present, `summon --version` only gives you part of the story, because it doesn't include the versions of known providers. It could be more useful if those versions were also printed.

The question of how to identify all installed providers is an interesting one, because any program or script could perhaps be a Summon provider. I propose that Summon provider installers ought to register themselves somehow, and that using Summon with any script as a provider should register that script.

When you run `summon --version` it can run `$provider --version` for each provider, and on a zero exit status it will include the provider's version alongside Summon's.

**Comment by behaviour** [comment]
Big thumbs up from me. Would prove invaluable when trying to manage provider installation via Ansible

**Comment by JakeQuilty** [comment]
PR: https://github.com/cyberark/summon/pull/136

**Comment by JakeQuilty** [comment]
New draft PR: https://github.com/cyberark/summon/pull/138
