### ISSUE TITLE
LastPass integration

### ISSUE THREAD

**Issue by mattthehearn** [cyberark/summon#62]
Are there any significant roadblocks that prevent "LastPass" integration?

**Comment by dustinmm80** [comment]
I'm not familiar with lastpass command line tooling options. What kind of integration would you like to see?

**Comment by mattthehearn** [comment]
Well, that's a good question. :) I'm not sure that LastPass has a CLI; it's generally best at saving passwords it scours from a browser, though in practice I use it to store all kinds of things (server logins, secure notes, etc.).  I'll check and see if they provide a CLI, or at least an API that can be securely accessed.

**Comment by dustinmm80** [comment]
@mattthehearn you may be in luck, looks like someone else has already created a provider. It's wraps the lastpass CLI, looks like. Have you seen this?

https://github.com/Lugoues/summon-lastpass

**Comment by mattthehearn** [comment]
Yep, already made my own fork and working on improving it.  Got distracted by some other stuff, but the lastpass CLI by itself is pretty awesome.

**Comment by dustinmm80** [comment]
Okay great, glad that's working for you. I'm going to close this issue out then. Cheers!
