### ISSUE TITLE
summon is buffering all of the process stdout output 

### ISSUE THREAD

**Issue by coderunner** [cyberark/summon#63]
We recently discovered that `summon` memory usage can increase significantly over the course of its lifetime. By looking at the code, it seems that it is tee-ing stdout to an internal buffer. For long running processes that prints to stdout (like a server using a console appender for example) or any process that writes a lot to stdout, this can lead to very high memory consumption by `summon` and ultimately, the death of the process.

To reproduce, use a script like 

```
#!/bin/sh

while true; do cat SOME_BIG_FILE; done
```
Then run this script with `summon`.

Found in `summon version 0.6.5`

**Comment by dustinmm80** [comment]
Good catch @coderunner - we don't run any long-lived processes with summon so hadn't noticed this. 

The problem appears to be here, as you said:
https://github.com/cyberark/summon/blob/master/command/subcommand.go#L17

Will take a look at this. I think we only buffered stdout to make testing easier.

**Comment by coderunner** [comment]
@dustinmm80 Thanks for taking a look! Hopefully, buffering `stdout` to memory is not needed outside of testing...which would make sense since `stdout` is forwarded to the console already.

**Comment by kgilpin** [comment]
I agree we should remove the stdout capture. If it’s needed for testing then there can be some kind of hidden/optional flag for it, but I think the tests can just use the normal stdout which is streamed.

**Comment by dustinmm80** [comment]
This has been fixed and released as summon v0.6.6, please let us know if this doesn't address your problem.

https://github.com/cyberark/summon/releases/tag/v0.6.6

**Comment by coderunner** [comment]
Thanks @dustinmm80 Much appreciated!!!
