### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by slimm609** [cyberark/summon#66]
We have seen this several times and it kills the process called from summon.   

fatal error: runtime: out of memory
runtime stack:
runtime.throw(0x5b044f, 0x16)
/usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sysMap(0xc49d500000, 0x7d0d0000, 0x0, 0x695738)
/usr/local/go/src/runtime/mem_linux.go:216 +0x1d0
runtime.(*mheap).sysAlloc(0x67d5c0, 0x7d0d0000, 0xc420247e18)
/usr/local/go/src/runtime/malloc.go:440 +0x374
runtime.(*mheap).grow(0x67d5c0, 0x3e868, 0x0)
/usr/local/go/src/runtime/mheap.go:774 +0x62
runtime.(*mheap).allocSpanLocked(0x67d5c0, 0x3e868, 0x44dc0a)
/usr/local/go/src/runtime/mheap.go:678 +0x44f
runtime.(*mheap).alloc_m(0x67d5c0, 0x3e868, 0x100000000, 0x0)
/usr/local/go/src/runtime/mheap.go:562 +0xe2
runtime.(*mheap).alloc.func1()
/usr/local/go/src/runtime/mheap.go:627 +0x4b
runtime.systemstack(0xc420247f10)
/usr/local/go/src/runtime/asm_amd64.s:343 +0xab
runtime.(*mheap).alloc(0x67d5c0, 0x3e868, 0x10100000000, 0x42f7c1)
/usr/local/go/src/runtime/mheap.go:628 +0xa0
runtime.largeAlloc(0x7d0cfd77, 0xc42001d301, 0xc4203f2680)
/usr/local/go/src/runtime/malloc.go:807 +0x93
runtime.mallocgc.func1()
/usr/local/go/src/runtime/malloc.go:702 +0x3e
runtime.systemstack(0xc42001c000)
/usr/local/go/src/runtime/asm_amd64.s:327 +0x79
runtime.mstart()
/usr/local/go/src/runtime/proc.go:1132
goroutine 143 [running]:
runtime.systemstack_switch()
/usr/local/go/src/runtime/asm_amd64.s:281 fp=0xc42045fc60 sp=0xc42045fc58
runtime.mallocgc(0x7d0cfd77, 0x574520, 0xc420416001, 0x0)
/usr/local/go/src/runtime/malloc.go:703 +0x930 fp=0xc42045fd00 sp=0xc42045fc60
runtime.makeslice(0x574520, 0x7d0cfd77, 0x7d0cfd77, 0x8ed, 0x8000, 0x0)
/usr/local/go/src/runtime/slice.go:54 +0x7b fp=0xc42045fd50 sp=0xc42045fd00
bytes.makeSlice(0x7d0cfd77, 0x0, 0x0, 0x0)
/usr/local/go/src/bytes/buffer.go:201 +0x77 fp=0xc42045fd90 sp=0xc42045fd50
bytes.(*Buffer).grow(0xc42040dce0, 0x8ed, 0x0)
/usr/local/go/src/bytes/buffer.go:109 +0x177 fp=0xc42045fde0 sp=0xc42045fd90
bytes.(*Buffer).Write(0xc42040dce0, 0xc4204a8000, 0x8ed, 0x8000, 0x8ed, 0x0, 0x0)
/usr/local/go/src/bytes/buffer.go:137 +0x41 fp=0xc42045fe10 sp=0xc42045fde0
io.(*multiWriter).Write(0xc4203c52e0, 0xc4204a8000, 0x8ed, 0x8000, 0x8ed, 0x0, 0x0)
/usr/local/go/src/io/multi.go:60 +0x72 fp=0xc42045fe70 sp=0xc42045fe10
io.copyBuffer(0x664420, 0xc4203c52e0, 0x6644a0, 0xc4200a84e0, 0xc4204a8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
/usr/local/go/src/io/io.go:392 +0x20b fp=0xc42045fed8 sp=0xc42045fe70
io.Copy(0x664420, 0xc4203c52e0, 0x6644a0, 0xc4200a84e0, 0x0, 0x0, 0x0)
/usr/local/go/src/io/io.go:360 +0x68 fp=0xc42045ff38 sp=0xc42045fed8
os/exec.(*Cmd).writerDescriptor.func1(0x0, 0x0)
/usr/local/go/src/os/exec/exec.go:254 +0x4d fp=0xc42045ff98 sp=0xc42045ff38
os/exec.(*Cmd).Start.func1(0xc4200a2420, 0xc4203c5340)
/usr/local/go/src/os/exec/exec.go:371 +0x27 fp=0xc42045ffd0 sp=0xc42045ff98
runtime.goexit()
/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42045ffd8 sp=0xc42045ffd0
created by os/exec.(*Cmd).Start
/usr/local/go/src/os/exec/exec.go:372 +0x4e4
goroutine 1 [syscall, 2358 minutes]:
syscall.Syscall6(0xf7, 0x1, 0x12d, 0xc4200b1688, 0x1000004, 0x0, 0x0, 0x7f24929e74b0, 0x0, 0xc4203c5320)
/usr/local/go/src/syscall/asm_linux_amd64.s:44 +0x5
os.(*Process).blockUntilWaitable(0xc420417bc0, 0xc4200a2420, 0xc4203c5340, 0x2)
/usr/local/go/src/os/wait_waitid.go:28 +0xa5
os.(*Process).wait(0xc420417bc0, 0x0, 0xc4200a84f8, 0xc4203c5220)
/usr/local/go/src/os/exec_unix.go:22 +0x4d
os.(*Process).Wait(0xc420417bc0, 0x0, 0x0, 0x5b7490)
/usr/local/go/src/os/exec.go:115 +0x2b
os/exec.(*Cmd).Wait(0xc4200a2420, 0x0, 0x0)
/usr/local/go/src/os/exec/exec.go:435 +0x62
os/exec.(*Cmd).Run(0xc4200a2420, 0x2, 0x2)
/usr/local/go/src/os/exec/exec.go:280 +0x5c
github.com/conjurinc/summon/command.runSubcommand(0xc42000e140, 0x2, 0x2, 0xc42006a480, 0x42, 0x48, 0x40, 0x30, 0x0, 0xc4200c6380)
/go/src/github.com/conjurinc/summon/command/subcommand.go:21 +0x1cf
github.com/conjurinc/summon/command.runAction(0xc42005a100, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/conjurinc/summon/command/action.go:130 +0x8ad
github.com/conjurinc/summon/command.glob..func1(0xc4200880e0)
/go/src/github.com/conjurinc/summon/command/action.go:47 +0x3fd
github.com/conjurinc/summon/vendor/github.com/codegangsta/cli.(*App).Run(0xc42008a000, 0xc42000e0b0, 0xb, 0xb, 0x0, 0x0)
/go/src/github.com/conjurinc/summon/vendor/github.com/codegangsta/cli/app.go:159 +0x54a
main.RunCLI(0x0, 0x0)
/go/src/github.com/conjurinc/summon/cli.go:27 +0x149
main.main()
/go/src/github.com/conjurinc/summon/main.go:9 +0x26

**Comment by kgilpin** [comment]
This looks like it could be caused by the bug that was just fixed in the
last release due to Summon collecting the sub process stdout

**Comment by slimm609** [comment]
awesome.   I will test.   Didn't realize 0.6.6 was out.    The error was with 0.6.5

**Comment by kgilpin** [comment]
OK cool. This is almost certainly the issue.

**Comment by slimm609** [comment]
looks to be resolved.  I will open a new issue if it happens again.   Thanks!
