### ISSUE TITLE
Inject `-e <SECTION>` as a new variable with that value into the subprocess

### ISSUE THREAD

**Issue by achiang** [cyberark/summon#92]
Feature request that if the `-e foo` switch is used, that the value `foo` be injected into the subprocess as well as a new variable - perhaps it would be something like `SUMMON_ENV` or similar.

The use case here is for the subprocess to exhibit different behavior, depending on which environment it detects while preventing the need to keep redefining the same variable in multiple sections.

Expected behavior:
```
$ summon -e foo env
...
SUMMON_ENV=foo
...

$ summon -e bar env
...
SUMMON_ENV=bar
...

$ summon env
...
<No extra variables>
...
```

Thanks for writing summon, we've found it very useful!

**Comment by sgnn7** [comment]
@achiang Wouldn't this be easily done with a non-`!var` variable in`secrets.yml` since the value is then used as a literal (see [here](https://github.com/cyberark/summon/blob/master/internal/command/action.go#L105-L106))? 

I haven't tried it but having a `secret.yml` with something like should work for this case unless I'm misunderstanding your need:
```
SUMMON_ENVIRONMENT: true
```

**Comment by achiang** [comment]
Ah, what I would like to do is create a `secrets.yml` that looks like this:

```yaml
production:
    DATABASE_URL: !var ...

sandbox:
    DATABASE_URL: !var ...

local:
    DATABASE_URL: !var ...
```

Then, I could key off `SUMMON_ENVIRONMENT == production` or `SUMMON_ENVIRONMENT == ssandbox` and do different things.

Does that explain the use case better?

**Comment by achiang** [comment]
@sgnn7 yes, that's exactly it. I would like to keep the `-e` behavior, but simply inject its value into the child process, so we can key behavior off it.

Thanks for the short term workaround, totally makes sense. Hoping you'll accept the feature request too. :)

Thanks!

**Comment by sgnn7** [comment]
Sounds good. I'll edit the original task description to explain a bit better what you would like to see. 👍

**Comment by sgnn7** [comment]
@achiang v0.6.11 released with this implemented.

https://github.com/cyberark/summon/releases/tag/v0.6.11
