### ISSUE TITLE
README file contains more information about the `!commands` available

### ISSUE THREAD

**Issue by garkler** [cyberark/summon#99]
The documentation should contain more information about the `!commands` available and their proper usage.

**Comment by mcanevet** [comment]
Where did you find any reference to this `!commands` tag? I can't find any neither in the doc, nor in the code:
https://github.com/cyberark/summon/blob/master/secretsyml/secretsyml.go#L23-L34

**Comment by ryanprior** [comment]
As far as I know, the options are `!var` and `!var:file`. We could resolve this issue by figuring out whether those are in fact the only two, and then updating the documentation accordingly.

**Comment by sgnn7** [comment]
Closing as "released". v0.8.1 can be found [here](https://github.com/cyberark/summon/releases/tag/v0.8.1). Info in question can be found [here](https://github.com/cyberark/summon/blob/master/README.md#secretsyml-flags).
